port: 8080

exclude: ['README.md', 'NOTES.md', 'Gemfile.lock', 'Gemfile', 'CNAME']

collections:
    authors:
        output: true

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"
